/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    ministries: Ministry;
    leadership: Leadership;
    sermons: Sermon;
    events: Event;
    members: Member;
    'worship-rota': WorshipRota;
    groups: Group;
    'contact-submissions': ContactSubmission;
    'prayer-requests': PrayerRequest;
    'visit-plans': VisitPlan;
    'volunteer-interests': VolunteerInterest;
    'leadership-interests': LeadershipInterest;
    'event-registrations': EventRegistration;
    'join-requests': JoinRequest;
    donations: Donation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    ministries: MinistriesSelect<false> | MinistriesSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'worship-rota': WorshipRotaSelect<false> | WorshipRotaSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'visit-plans': VisitPlansSelect<false> | VisitPlansSelect<true>;
    'volunteer-interests': VolunteerInterestsSelect<false> | VolunteerInterestsSelect<true>;
    'leadership-interests': LeadershipInterestsSelect<false> | LeadershipInterestsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    'join-requests': JoinRequestsSelect<false> | JoinRequestsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ta' | 'kn') | ('en' | 'ta' | 'kn')[];
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'ministries-page': MinistriesPage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'sermons-page': SermonsPage;
    'events-page': EventsPage;
    'schedule-page': SchedulePage;
    'live-page': LivePage;
    'visit-page': VisitPage;
    'directions-page': DirectionsPage;
    'prayer-page': PrayerPage;
    'rota-page': RotaPage;
    'volunteer-page': VolunteerPage;
    'groups-page': GroupsPage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'ministries-page': MinistriesPageSelect<false> | MinistriesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'sermons-page': SermonsPageSelect<false> | SermonsPageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'schedule-page': SchedulePageSelect<false> | SchedulePageSelect<true>;
    'live-page': LivePageSelect<false> | LivePageSelect<true>;
    'visit-page': VisitPageSelect<false> | VisitPageSelect<true>;
    'directions-page': DirectionsPageSelect<false> | DirectionsPageSelect<true>;
    'prayer-page': PrayerPageSelect<false> | PrayerPageSelect<true>;
    'rota-page': RotaPageSelect<false> | RotaPageSelect<true>;
    'volunteer-page': VolunteerPageSelect<false> | VolunteerPageSelect<true>;
    'groups-page': GroupsPageSelect<false> | GroupsPageSelect<true>;
  };
  locale: 'en' | 'ta' | 'kn';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries".
 */
export interface Ministry {
  id: number;
  name: string;
  /**
   * URL segment, e.g. "youth" for /ministries/youth
   */
  slug: string;
  description: string;
  image: number | Media;
  /**
   * Icon shown in the homepage "Find Your Place" band — separate from the filter categories below.
   */
  icon: 'youth' | 'children' | 'women' | 'men' | 'worship' | 'outreach' | 'groups';
  /**
   * A ministry can belong to more than one filter category
   */
  categories: ('adults' | 'kids-youth' | 'service')[];
  ctaLabel?: string | null;
  /**
   * Powers a real mailto: link on "Join Ministry" — clicking it opens the visitor’s email client to reach out directly, same pattern as Groups’ "Join Group".
   */
  contactEmail: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  /**
   * URL segment for the bio page, e.g. "david-mitchell" for /about/david-mitchell
   */
  slug: string;
  /**
   * e.g. "Lead Pastor"
   */
  roleLabel: string;
  photo: number | Media;
  bio: string;
  /**
   * Controls which of the three card layouts renders on the About page bento grid.
   */
  variant: 'photo-left' | 'photo-top' | 'avatar';
  /**
   * Shows a "Read Full Bio" link pointing at this person's /about/[slug] page.
   */
  hasFullBio?: boolean | null;
  /**
   * Controls bento-grid position. The current layout assumes exactly 4 leaders (positions 0-3); revisit the layout if the team grows beyond that.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  slug: string;
  /**
   * e.g. "The Parables Series" or "Standalone Message" — shown as the gold eyebrow and used for the Series filter.
   */
  seriesLabel: string;
  description: string;
  /**
   * e.g. "Luke 15:11-32"
   */
  scripture: string;
  /**
   * Initials for the avatar badge are generated automatically from this name — no separate field needed.
   */
  speakerName: string;
  /**
   * Free-text tag, e.g. "Grace", "Faith", "Comfort" — powers the Topic filter.
   */
  topic: string;
  date: string;
  /**
   * e.g. "45:20"
   */
  duration: string;
  thumbnail: number | Media;
  /**
   * Paste the full YouTube URL for this sermon (whatever’s in your browser’s address bar or the "Share" button works) — not just the video ID.
   */
  youtubeUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL segment, e.g. "awaken-2026" for /events/awaken-2026 — lowercase, hyphens instead of spaces, no punctuation.
   */
  slug: string;
  /**
   * Drives the filter, the badge color/label, and the calendar — no separate fields needed for those.
   */
  category: 'youth' | 'missions' | 'conferences' | 'worship';
  startDate: string;
  /**
   * Leave blank for a single-day event. Setting this marks every day in the range gold on the calendar (multi-day conference/retreat) instead of a single navy dot.
   */
  endDate?: string | null;
  /**
   * e.g. "7:00 PM - 9:00 PM" or "All Day"
   */
  time: string;
  location: string;
  /**
   * e.g. "Free Registration" or "$25 per person" — shown on the event detail page’s info bar.
   */
  cost?: string | null;
  description: string;
  /**
   * Not shown on the /events archive card itself, but used by the Homepage's "Upcoming at Bethesda" cards.
   */
  image?: (number | null) | Media;
  actions?:
    | {
        label: string;
        href: string;
        variant: 'solid' | 'outline';
        id?: string | null;
      }[]
    | null;
  /**
   * When checked, the event detail page shows a real, members-only registration form (name/email pre-filled from the session, an explicit attendance confirmation, and a real record members can see and cancel from their Dashboard) instead of just the Buttons above. Leave unchecked for events that only need an informational link — e.g. "Learn More" pointing somewhere external.
   */
  requiresRegistration?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public site member accounts — separate from Users (CMS admin accounts). Members cannot log into /admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  avatar?: (number | null) | Media;
  /**
   * Select from the real Groups collection — schedule and location are pulled from the group itself, not re-entered here. Also populated automatically when a Join Request for this member is approved — see the Join Requests collection.
   */
  myGroups?: (number | Group)[] | null;
  /**
   * Populated automatically when a Join Request for this member is approved — see the Join Requests collection. Editable here directly too, if a membership needs adding or removing outside that flow.
   */
  myMinistries?: (number | Ministry)[] | null;
  /**
   * Leave the role blank if this member has no upcoming shift — the dashboard hides the card entirely rather than showing an empty one.
   */
  volunteerShift?: {
    /**
     * e.g. "This Sunday"
     */
    dayLabel?: string | null;
    /**
     * e.g. "Greeter Team"
     */
    role?: string | null;
    /**
     * e.g. "9:00 AM"
     */
    time?: string | null;
    /**
     * e.g. "Main Entrance, South Wing"
     */
    location?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  title: string;
  slug: string;
  /**
   * e.g. "Young Adults", "Families", "Open to All"
   */
  badgeLabel: string;
  /**
   * Drives the sidebar filter — the option set is fixed in code, matching the design.
   */
  category: 'worship' | 'youth' | 'care-groups' | 'kids' | 'care';
  description: string;
  /**
   * e.g. "Tuesdays, 7:00 PM"
   */
  schedule: string;
  location: string;
  leaderName: string;
  leaderPhoto?: (number | null) | Media;
  /**
   * Powers a real mailto: link on "Join Group" — no request-to-join backend exists, so this is the honest, functional middle ground.
   */
  contactEmail: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worship-rota".
 */
export interface WorshipRota {
  id: number;
  date: string;
  /**
   * e.g. "Main Service" — powers the Ministry filter dropdown, derived automatically from existing entries rather than a fixed list.
   */
  ministry: string;
  /**
   * e.g. "10:00 AM"
   */
  serviceTime: string;
  sermon: {
    speakerName: string;
    speakerPhoto?: (number | null) | Media;
    /**
     * Shows "(Guest)" next to the name
     */
    isGuest?: boolean | null;
    /**
     * Sermon title or topic
     */
    title: string;
  };
  worshipTeam: {
    teamName: string;
    leaderName: string;
    /**
     * Optional small pill, e.g. "Full Ensemble"
     */
    badge?: string | null;
    /**
     * Team member photos — the page shows up to 3 with a "+N" overflow for the rest.
     */
    members?:
      | {
          photo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Real member accounts serving on this rota entry (leader, team, or anyone else scheduled) — separate from the photo-only team display above. This is what powers "my serving schedule" on a member’s Dashboard; the photo grid is purely visual and doesn’t need to match this list exactly.
   */
  assignedMembers?: (number | Member)[] | null;
  specialItems?:
    | {
        /**
         * e.g. "Offering Song"
         */
        label: string;
        personName: string;
        /**
         * e.g. "Vocalist" — optional
         */
        roleLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions. Contains PII — readable only by CMS admins via /admin, not exposed on the public API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  subject: string;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Prayer request submissions. Readable only by CMS admins — there’s no separate "prayer team" role modeled yet, so isPrivate is informational for triage rather than a second access tier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  request: string;
  /**
   * From the "Keep this request private" checkbox
   */
  isPrivate?: boolean | null;
  status?: ('new' | 'praying' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Plan Your Visit submissions. Contains PII — admin-only, same as Contact and Prayer Requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans".
 */
export interface VisitPlan {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  dateOfVisit: string;
  numberInParty: string;
  wantsHost?: boolean | null;
  status?: ('new' | 'confirmed' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the featured "high need" area’s interest form on /volunteer. Admin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-interests".
 */
export interface VolunteerInterest {
  id: number;
  name: string;
  email: string;
  /**
   * The service area title this came from, e.g. "Bethesda Kids"
   */
  areaOfInterest: string;
  status?: ('new' | 'contacted' | 'placed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from Ministries’ members-only "Interested in Leading?" form. Unlike the other submission collections, create itself requires a real member session, not just public access — matching the UI gate all the way through.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-interests".
 */
export interface LeadershipInterest {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  areaOfInterest: string;
  /**
   * Set automatically from the logged-in session — never trusted from client input.
   */
  submittedByMember?: (number | null) | Member;
  status?: ('new' | 'contacted' | 'placed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real event registrations, member-only. Unlike the other submission collections, both read and update are restricted per-document — a member can only see/cancel their own registrations, not everyone’s.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  /**
   * Set automatically from the logged-in session — never trusted from client input.
   */
  member: number | Member;
  event: number | Event;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  numberOfAttendees: '1' | '2' | '3' | '4' | '5+';
  /**
   * Dietary requirements or other special requests — optional.
   */
  specialRequests?: string | null;
  status?: ('registered' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real, trackable requests to join a Ministry or Group — replaces the previous mailto: links, which nobody could confirm had actually been sent or seen. Pending requests need action; approving one automatically adds the member to that Ministry/Group (their Dashboard reflects it immediately) rather than requiring a separate manual step.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-requests".
 */
export interface JoinRequest {
  id: number;
  /**
   * Set automatically from the logged-in session — never trusted from client input.
   */
  member: number | Member;
  /**
   * The specific Ministry or Group being requested.
   */
  target:
    | {
        relationTo: 'ministries';
        value: number | Ministry;
      }
    | {
        relationTo: 'groups';
        value: number | Group;
      };
  memberName: string;
  memberEmail: string;
  status?: ('pending' | 'approved' | 'declined') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real, verified donation records — only created after Razorpay’s payment signature has been cryptographically checked server-side, so a record here means a payment genuinely succeeded, not just that a checkout was opened.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  /**
   * In rupees (₹), not paise.
   */
  amount: number;
  fund: string;
  donorName: string;
  donorEmail: string;
  donorPhone?: string | null;
  /**
   * Set automatically when the donor happens to be logged in at the time of giving — giving itself is never member-gated.
   */
  member?: (number | null) | Member;
  razorpayOrderId: string;
  razorpayPaymentId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'ministries';
        value: number | Ministry;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'worship-rota';
        value: number | WorshipRota;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'visit-plans';
        value: number | VisitPlan;
      } | null)
    | ({
        relationTo: 'volunteer-interests';
        value: number | VolunteerInterest;
      } | null)
    | ({
        relationTo: 'leadership-interests';
        value: number | LeadershipInterest;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'join-requests';
        value: number | JoinRequest;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries_select".
 */
export interface MinistriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  icon?: T;
  categories?: T;
  ctaLabel?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  roleLabel?: T;
  photo?: T;
  bio?: T;
  variant?: T;
  hasFullBio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seriesLabel?: T;
  description?: T;
  scripture?: T;
  speakerName?: T;
  topic?: T;
  date?: T;
  duration?: T;
  thumbnail?: T;
  youtubeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  startDate?: T;
  endDate?: T;
  time?: T;
  location?: T;
  cost?: T;
  description?: T;
  image?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  requiresRegistration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  myGroups?: T;
  myMinistries?: T;
  volunteerShift?:
    | T
    | {
        dayLabel?: T;
        role?: T;
        time?: T;
        location?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worship-rota_select".
 */
export interface WorshipRotaSelect<T extends boolean = true> {
  date?: T;
  ministry?: T;
  serviceTime?: T;
  sermon?:
    | T
    | {
        speakerName?: T;
        speakerPhoto?: T;
        isGuest?: T;
        title?: T;
      };
  worshipTeam?:
    | T
    | {
        teamName?: T;
        leaderName?: T;
        badge?: T;
        members?:
          | T
          | {
              photo?: T;
              id?: T;
            };
      };
  assignedMembers?: T;
  specialItems?:
    | T
    | {
        label?: T;
        personName?: T;
        roleLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badgeLabel?: T;
  category?: T;
  description?: T;
  schedule?: T;
  location?: T;
  leaderName?: T;
  leaderPhoto?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  request?: T;
  isPrivate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-plans_select".
 */
export interface VisitPlansSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  dateOfVisit?: T;
  numberInParty?: T;
  wantsHost?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-interests_select".
 */
export interface VolunteerInterestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  areaOfInterest?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-interests_select".
 */
export interface LeadershipInterestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  areaOfInterest?: T;
  submittedByMember?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  member?: T;
  event?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  numberOfAttendees?: T;
  specialRequests?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-requests_select".
 */
export interface JoinRequestsSelect<T extends boolean = true> {
  member?: T;
  target?: T;
  memberName?: T;
  memberEmail?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  amount?: T;
  fund?: T;
  donorName?: T;
  donorEmail?: T;
  donorPhone?: T;
  member?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for the public homepage. Sections that pull from other collections (Latest Sermons, Upcoming Events, Find Your Place / Ministries) live in those collections instead, once built.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    badgeText: string;
    /**
     * A line break here becomes a visual line break on the homepage (e.g. "A Place to Belong," on one line, "A Place to Grow" on the next).
     */
    heading: string;
    subtext: string;
    primaryButtonLabel: string;
    primaryButtonHref: string;
    secondaryButtonLabel: string;
    secondaryButtonHref: string;
    backgroundImage: number | Media;
    /**
     * Optional. A short (5–15s), muted, looping clip to play instead of the still image above. The image is still required — it’s used as the video’s poster frame while it loads, and shown instead of the video entirely for visitors with a reduced-motion preference set on their device. Upload as MP4 (H.264) — the safest, most broadly compatible format.
     */
    backgroundVideo?: (number | null) | Media;
    /**
     * Optional. The same clip as above, encoded as WebM (VP9) — typically a smaller file at equivalent quality. When present, browsers that support WebM use this instead of the MP4; every browser still falls back to the MP4 automatically if this is left blank or if WebM isn’t supported.
     */
    backgroundVideoWebm?: (number | null) | Media;
  };
  quickLinks?:
    | {
        icon: 'watch' | 'calendar' | 'give' | 'prayer';
        title: string;
        subtext: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  serviceTimes?:
    | {
        /**
         * e.g. "8:00 AM"
         */
        time: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  pastorWelcome: {
    photo: number | Media;
    eyebrow: string;
    heading: string;
    quote: string;
    name: string;
    title: string;
  };
  givingBreakdown?:
    | {
        label: string;
        percentage: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide identity, contact info, and office hours — used on the Footer, Contact page, Give page, and Homepage Visit Us section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  churchName: string;
  tagline: string;
  address?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  phone: string;
  email: string;
  /**
   * Optional — leave blank to auto-generate a working map from the address above. Only paste a Google Maps embed URL here if you want a more precisely placed pin (Google Maps > Share > Embed a map > copy the src from the iframe code).
   */
  mapEmbedUrl?: string | null;
  officeHours?:
    | {
        label: string;
        hours: string;
        /**
         * Styles this row gold, e.g. for Sunday services
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero and Small Groups section for /ministries. Individual ministries live in the Ministries collection instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries-page".
 */
export interface MinistriesPage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
  };
  smallGroups: {
    heading: string;
    description: string;
    features?:
      | {
          icon: 'discussion' | 'support';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  areaOfInterestOptions?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, Core Values, and Journey timeline for /about. Leadership team lives in the Leadership collection instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * A line break here becomes a visual line break on the page.
     */
    heading: string;
    subtext: string;
    ctaLabel: string;
    ctaHref: string;
  };
  coreValues?:
    | {
        icon: 'book' | 'heart' | 'community' | 'globe';
        accent: 'blue' | 'gold';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  journey?:
    | {
        year: string;
        title: string;
        description: string;
        dotAccent: 'blue' | 'gold';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero and form options for /contact. Address, phone, office hours, and map come from Site Settings instead — not duplicated here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
  };
  subjectOptions?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  visit: {
    campusName: string;
    directionsHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Featured hero and podcast CTA for /sermons. The archive list itself lives in the Sermons collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-page".
 */
export interface SermonsPage {
  id: number;
  hero: {
    badge: string;
    /**
     * The sermon featured here and on the Homepage’s "Latest Word" section. Its title, description, image, date, speaker, and video all come directly from the sermon itself — nothing to retype.
     */
    featuredSermon: number | Sermon;
  };
  podcastCta: {
    heading: string;
    description: string;
    links?:
      | {
          label: string;
          href: string;
          icon: 'headphones' | 'waveform';
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero, Community Focus, and newsletter CTA for /events. The event list and calendar are driven by the Events collection instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  hero: {
    badge: string;
    /**
     * The event this hero promotes. Its title, description, image, and registration link are pulled directly from the event itself — nothing to retype, and nothing that can drift out of sync or point to the wrong place.
     */
    featuredEvent: number | Event;
  };
  communityFocus?:
    | {
        title: string;
        description: string;
        image: number | Media;
        linkLabel: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  newsletterCta: {
    heading: string;
    subtext: string;
    placeholder: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /schedule — the Weekly Services list and Special Services (e.g. "First Fridays") are the parts most worth keeping current.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-page".
 */
export interface SchedulePage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
  };
  weeklyServices?:
    | {
        /**
         * e.g. "Sunday Morning"
         */
        name: string;
        /**
         * e.g. "9:00 AM"
         */
        time: string;
        badgeLabel: 'In-Person' | 'Hybrid';
        /**
         * e.g. "Traditional Liturgy"
         */
        serviceTitle: string;
        description: string;
        location: string;
        id?: string | null;
      }[]
    | null;
  quote: {
    quote: string;
    reference: string;
  };
  /**
   * The part of this page most likely to need regular updates — e.g. "First Fridays," seasonal events.
   */
  specialServices?:
    | {
        title: string;
        /**
         * e.g. "1st Friday of every month, 8:00 PM"
         */
        schedule: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /live. The "stream" fields (title, speaker, live status) are meant to be updated weekly. Sample chat messages and sermon notes are NOT here on purpose — that’s decorative placeholder UI for a chat feature with no real backend yet; putting fake messages in the CMS would only confuse editors about what’s real.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-page".
 */
export interface LivePage {
  id: number;
  stream: {
    /**
     * Purely decorative now — controls only the "Live Now" badge/label text below. The video itself always shows whatever’s actually live on your channel automatically (or your most recent stream when nothing’s live), so this can’t drift out of sync with reality the way it used to.
     */
    isLive?: boolean | null;
    /**
     * Your YouTube Channel ID (starts with "UC") — not your @handle. The player automatically shows whatever’s currently live on this channel, with zero need to update this per stream.
     */
    youtubeChannelId: string;
    liveLabel: string;
    /**
     * This week’s sermon title
     */
    title: string;
    speaker: string;
    bookReference: string;
  };
  onlineGiving: {
    heading: string;
    description: string;
    buttonLabel: string;
    buttonHref: string;
  };
  inPerson: {
    heading: string;
    serviceTimes?:
      | {
          label: string;
          time: string;
          id?: string | null;
        }[]
      | null;
    directionsLabel: string;
    directionsHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /visit. The form itself (fields, dropdown options) stays code-owned — only the surrounding editorial content lives here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-page".
 */
export interface VisitPage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
  };
  whatToExpect?:
    | {
        icon: 'parking' | 'kids' | 'coffee';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  serviceTimes?:
    | {
        label: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /directions. Address, phone, and email are NOT here — they come from Site Settings, so there’s one place to update them, not two.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions-page".
 */
export interface DirectionsPage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
  };
  serviceTimes?:
    | {
        label: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  needHelp: {
    heading: string;
    description: string;
  };
  drivingDirections?:
    | {
        /**
         * e.g. "From the North (City Center)"
         */
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  parkingItems?:
    | {
        icon: 'car' | 'accessibility' | 'bus';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /prayer. The request form itself stays code-owned (see the caveat in PrayerForm.tsx about real submissions needing their own collection later).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-page".
 */
export interface PrayerPage {
  id: number;
  hero: {
    heading: string;
    scriptureQuote: string;
    scriptureReference: string;
    description: string;
    image: number | Media;
  };
  prayerTeam: {
    heading: string;
    description: string;
    avatarImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    additionalCount: number;
  };
  intercedeCard: {
    heading: string;
    description: string;
    linkLabel: string;
    linkHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the members-only /ministries/rota page. The "Worship Rota – [Month]" heading is generated from the selected month filter, not stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rota-page".
 */
export interface RotaPage {
  id: number;
  eyebrow: string;
  worshipGuidelines: {
    heading: string;
    description: string;
    linkLabel: string;
    linkHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /volunteer. The featured "high need" card’s interest form (Name/Email) is static UI, not wired to a backend yet — same caveat as the Contact and Prayer forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page".
 */
export interface VolunteerPage {
  id: number;
  hero: {
    badge: string;
    heading: string;
    subtext: string;
    buttonLabel: string;
    buttonHref: string;
    backgroundImage: number | Media;
  };
  areas?:
    | {
        variant: 'image' | 'plain' | 'featured';
        icon: 'worship' | 'hospitality' | 'outreach' | 'kids';
        title: string;
        description: string;
        image?: (number | null) | Media;
        signUpLabel?: string | null;
        signUpHref?: string | null;
        /**
         * e.g. "High Need" — leave blank to hide the badge
         */
        highNeedLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  quote: {
    quote: string;
    reference: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /groups. The category sidebar and "Filters" button are structural/code-owned, matching the Groups collection’s fixed category options.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups-page".
 */
export interface GroupsPage {
  id: number;
  hero: {
    heading: string;
    subtext: string;
    searchPlaceholder: string;
    backgroundImage: number | Media;
  };
  quote: {
    quote: string;
    reference: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badgeText?: T;
        heading?: T;
        subtext?: T;
        primaryButtonLabel?: T;
        primaryButtonHref?: T;
        secondaryButtonLabel?: T;
        secondaryButtonHref?: T;
        backgroundImage?: T;
        backgroundVideo?: T;
        backgroundVideoWebm?: T;
      };
  quickLinks?:
    | T
    | {
        icon?: T;
        title?: T;
        subtext?: T;
        href?: T;
        id?: T;
      };
  serviceTimes?:
    | T
    | {
        time?: T;
        label?: T;
        id?: T;
      };
  pastorWelcome?:
    | T
    | {
        photo?: T;
        eyebrow?: T;
        heading?: T;
        quote?: T;
        name?: T;
        title?: T;
      };
  givingBreakdown?:
    | T
    | {
        label?: T;
        percentage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  churchName?: T;
  tagline?: T;
  address?:
    | T
    | {
        line?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  mapEmbedUrl?: T;
  officeHours?:
    | T
    | {
        label?: T;
        hours?: T;
        highlight?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries-page_select".
 */
export interface MinistriesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  smallGroups?:
    | T
    | {
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  areaOfInterestOptions?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  coreValues?:
    | T
    | {
        icon?: T;
        accent?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  journey?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        dotAccent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  subjectOptions?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  visit?:
    | T
    | {
        campusName?: T;
        directionsHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons-page_select".
 */
export interface SermonsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        featuredSermon?: T;
      };
  podcastCta?:
    | T
    | {
        heading?: T;
        description?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        featuredEvent?: T;
      };
  communityFocus?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        linkLabel?: T;
        href?: T;
        id?: T;
      };
  newsletterCta?:
    | T
    | {
        heading?: T;
        subtext?: T;
        placeholder?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-page_select".
 */
export interface SchedulePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  weeklyServices?:
    | T
    | {
        name?: T;
        time?: T;
        badgeLabel?: T;
        serviceTitle?: T;
        description?: T;
        location?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        quote?: T;
        reference?: T;
      };
  specialServices?:
    | T
    | {
        title?: T;
        schedule?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-page_select".
 */
export interface LivePageSelect<T extends boolean = true> {
  stream?:
    | T
    | {
        isLive?: T;
        youtubeChannelId?: T;
        liveLabel?: T;
        title?: T;
        speaker?: T;
        bookReference?: T;
      };
  onlineGiving?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  inPerson?:
    | T
    | {
        heading?: T;
        serviceTimes?:
          | T
          | {
              label?: T;
              time?: T;
              id?: T;
            };
        directionsLabel?: T;
        directionsHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visit-page_select".
 */
export interface VisitPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  whatToExpect?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  serviceTimes?:
    | T
    | {
        label?: T;
        time?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "directions-page_select".
 */
export interface DirectionsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  serviceTimes?:
    | T
    | {
        label?: T;
        time?: T;
        id?: T;
      };
  needHelp?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  drivingDirections?:
    | T
    | {
        heading?: T;
        text?: T;
        id?: T;
      };
  parkingItems?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-page_select".
 */
export interface PrayerPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        scriptureQuote?: T;
        scriptureReference?: T;
        description?: T;
        image?: T;
      };
  prayerTeam?:
    | T
    | {
        heading?: T;
        description?: T;
        avatarImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        additionalCount?: T;
      };
  intercedeCard?:
    | T
    | {
        heading?: T;
        description?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rota-page_select".
 */
export interface RotaPageSelect<T extends boolean = true> {
  eyebrow?: T;
  worshipGuidelines?:
    | T
    | {
        heading?: T;
        description?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page_select".
 */
export interface VolunteerPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        subtext?: T;
        buttonLabel?: T;
        buttonHref?: T;
        backgroundImage?: T;
      };
  areas?:
    | T
    | {
        variant?: T;
        icon?: T;
        title?: T;
        description?: T;
        image?: T;
        signUpLabel?: T;
        signUpHref?: T;
        highNeedLabel?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        quote?: T;
        reference?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups-page_select".
 */
export interface GroupsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subtext?: T;
        searchPlaceholder?: T;
        backgroundImage?: T;
      };
  quote?:
    | T
    | {
        quote?: T;
        reference?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}